# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "<%= config.operatingSystemDistribution %>"
  config.vm.network "private_network", ip: "<%= config.privateIp %>"
  <%_ if (config.operatingSystemDistribution === 'centos/7') { _%>
  config.vm.synced_folder ".", "/vagrant", type: "virtualbox"
  <%_ } _%>
  config.vm.hostname = "<%= config.hostname %>"
  # config.hostsupdater.aliases = []
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
    # vb.cpus = 2
  end
  config.puppet_install.puppet_version = :latest
  config.vm.provision "puppet" do |puppet|
    puppet.environment_path = "puppet/environments"
    puppet.environment = "local"
    puppet.module_path = "puppet/modules"
    puppet.options = "--verbose --debug"
  end
end
