# -*- mode: ruby -*-
# vi: set ft=ruby :

require "json"
projectConfig = JSON.parse(File.read(File.join(File.dirname(__FILE__), 'config.json')))

Vagrant.require_version ">= 1.9.2"
Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.network "private_network", :ip => projectConfig["vagrant"]["network"]["privateIp"]
  config.vm.synced_folder "./public", "/var/www/html"
  config.vm.hostname = projectConfig["hostname"]
  config.hostsupdater.aliases = projectConfig["aliases"]
  config.vm.provider "virtualbox" do |vb|
    vb.memory = projectConfig["vagrant"]["settings"]["memory"]
  end
  config.puppet_install.puppet_version = :latest
  config.librarian_puppet.puppetfile_dir = "puppet"
  config.librarian_puppet.placeholder_filename = ".keep"
  config.vm.provision "puppet" do |puppet|
    puppet.environment_path = "puppet/environments"
    puppet.environment = "local"
    puppet.module_path = "puppet/modules"
    puppet.options = "--verbose --debug"
  end
end
